🐛 Make required options required
When the user does not give, e.g. an input image, the program just
reports a cryptic error message.

Fix this and make the CLI friendlier by requiring the options using the
Click API. Now the CLI gives a useful error:

  Error: Missing option '--image' / '-i'.